# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ref', '0001_initial'),
        ('nibrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShrCircumstances',
            fields=[
                ('circumstances_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('circumstances_code', models.CharField(max_length=2)),
                ('sub_code', models.CharField(blank=True, max_length=1, null=True)),
                ('circumstances_name', models.CharField(max_length=100)),
                ('sub_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'shr_circumstances',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShrIncident',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('homicide_code', models.CharField(blank=True, max_length=1, null=True)),
                ('incident_num', models.CharField(blank=True, max_length=3, null=True)),
                ('incident_status', models.SmallIntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_incident_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shr_incident',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShrMonth',
            fields=[
                ('shr_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('data_home', models.CharField(max_length=1)),
                ('source_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefAgency')),
            ],
            options={
                'db_table': 'shr_month',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShrOffender',
            fields=[
                ('offender_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offender_num', models.CharField(blank=True, max_length=20, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_offender_id', models.BigIntegerField(blank=True, null=True)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsAge')),
                ('ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsEthnicity')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefRace')),
            ],
            options={
                'db_table': 'shr_offender',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShrOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
                ('circumstances', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shr.ShrCircumstances')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shr.ShrIncident')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shr.ShrOffender')),
            ],
            options={
                'db_table': 'shr_offense',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShrRelationship',
            fields=[
                ('relationship_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('relationship_code', models.CharField(blank=True, max_length=2, null=True)),
                ('relationship_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'shr_relationship',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShrSituation',
            fields=[
                ('situation_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('situation_code', models.CharField(blank=True, max_length=1, null=True)),
                ('situation_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'shr_situation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ShrVictim',
            fields=[
                ('victim_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('victim_num', models.CharField(blank=True, max_length=20, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_victim_id', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsAge')),
                ('ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsEthnicity')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefRace')),
            ],
            options={
                'db_table': 'shr_victim',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='shroffense',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shr.ShrRelationship'),
        ),
        migrations.AddField(
            model_name='shroffense',
            name='victim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shr.ShrVictim'),
        ),
        migrations.AddField(
            model_name='shroffense',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsWeaponType'),
        ),
        migrations.AddField(
            model_name='shrincident',
            name='shr_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shr.ShrMonth'),
        ),
        migrations.AddField(
            model_name='shrincident',
            name='situation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shr.ShrSituation'),
        ),
        migrations.AlterUniqueTogether(
            name='shrmonth',
            unique_together=set([('agency', 'data_year', 'month_num', 'data_home')]),
        ),
        migrations.AlterUniqueTogether(
            name='shrincident',
            unique_together=set([('shr_month', 'incident_num', 'data_home')]),
        ),
    ]
