# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShrCircumstances',
            fields=[
                ('circumstances_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('circumstances_code', models.CharField(max_length=2)),
                ('sub_code', models.CharField(blank=True, max_length=1, null=True)),
                ('circumstances_name', models.CharField(max_length=100)),
                ('sub_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'shr_circumstances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShrIncident',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('homicide_code', models.CharField(blank=True, max_length=1, null=True)),
                ('incident_num', models.CharField(blank=True, max_length=3, null=True)),
                ('incident_status', models.SmallIntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_incident_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shr_incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShrMonth',
            fields=[
                ('shr_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('data_home', models.CharField(max_length=1)),
                ('source_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shr_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShrOffender',
            fields=[
                ('offender_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offender_num', models.CharField(blank=True, max_length=20, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_offender_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shr_offender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShrOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shr_offense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShrRelationship',
            fields=[
                ('relationship_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('relationship_code', models.CharField(blank=True, max_length=2, null=True)),
                ('relationship_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'shr_relationship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShrSituation',
            fields=[
                ('situation_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('situation_code', models.CharField(blank=True, max_length=1, null=True)),
                ('situation_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'shr_situation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShrVictim',
            fields=[
                ('victim_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('victim_num', models.CharField(blank=True, max_length=20, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_victim_id', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shr_victim',
                'managed': False,
            },
        ),
    ]
