# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArsonMonth',
            fields=[
                ('arson_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('data_home', models.CharField(max_length=1)),
                ('source_flag', models.CharField(max_length=1)),
                ('reported_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('month_included_in', models.SmallIntegerField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arson_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArsonMonthBySubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_count', models.IntegerField(blank=True, null=True)),
                ('reported_status', models.SmallIntegerField(blank=True, null=True)),
                ('unfounded_count', models.IntegerField(blank=True, null=True)),
                ('unfounded_status', models.SmallIntegerField(blank=True, null=True)),
                ('actual_count', models.IntegerField(blank=True, null=True)),
                ('actual_status', models.SmallIntegerField(blank=True, null=True)),
                ('cleared_count', models.IntegerField(blank=True, null=True)),
                ('cleared_status', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_cleared_count', models.IntegerField(blank=True, null=True)),
                ('juvenile_cleared_status', models.SmallIntegerField(blank=True, null=True)),
                ('uninhabited_count', models.IntegerField(blank=True, null=True)),
                ('uninhabited_status', models.SmallIntegerField(blank=True, null=True)),
                ('est_damage_value', models.BigIntegerField(blank=True, null=True)),
                ('est_damage_value_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arson_month_by_subcat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArsonSubcategory',
            fields=[
                ('subcategory_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('subcat_xml_path', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'arson_subcategory',
            },
        ),
        migrations.CreateModel(
            name='ArsonSubclassification',
            fields=[
                ('subclass_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('subclass_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subclass_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('subclass_xml_path', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'arson_subclassification',
            },
        ),
        migrations.CreateModel(
            name='AsrAgeRange',
            fields=[
                ('age_range_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age_range_name', models.CharField(blank=True, max_length=20, null=True)),
                ('age_range_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('juvenile_flag', models.CharField(max_length=1)),
                ('ff_sort_order', models.CharField(blank=True, max_length=3, null=True)),
                ('age_sex', models.CharField(blank=True, max_length=1, null=True)),
                ('xml_code', models.CharField(blank=True, max_length=2001, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'asr_age_range',
            },
        ),
        migrations.CreateModel(
            name='AsrAgeSexSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrest_count', models.IntegerField(blank=True, null=True)),
                ('arrest_status', models.SmallIntegerField(blank=True, null=True)),
                ('active_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asr_age_sex_subcat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsrEthnicity',
            fields=[
                ('ethnicity_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ethnicity_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnicity_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ff_sort_order', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'asr_ethnicity',
            },
        ),
        migrations.CreateModel(
            name='AsrEthnicityOffense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juvenile_flag', models.CharField(max_length=1)),
                ('arrest_count', models.IntegerField(blank=True, null=True)),
                ('arrest_status', models.SmallIntegerField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asr_ethnicity_offense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsrMonth',
            fields=[
                ('asr_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('source_flag', models.CharField(max_length=1)),
                ('reported_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'asr_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AsrOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_name', models.CharField(blank=True, max_length=100, null=True)),
                ('offense_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('total_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'asr_offense',
            },
        ),
        migrations.CreateModel(
            name='AsrOffenseCategory',
            fields=[
                ('offense_cat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_cat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('offense_cat_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'asr_offense_category',
            },
        ),
        migrations.CreateModel(
            name='AsrOffenseSubcat',
            fields=[
                ('offense_subcat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_subcat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('offense_subcat_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('srs_offense_code', models.CharField(blank=True, max_length=3, null=True)),
                ('master_offense_code', models.SmallIntegerField(blank=True, null=True)),
                ('total_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('adult_juv_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'asr_offense_subcat',
            },
        ),
        migrations.CreateModel(
            name='AsrRaceOffenseSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juvenile_flag', models.CharField(max_length=1)),
                ('arrest_count', models.IntegerField(blank=True, null=True)),
                ('arrest_status', models.SmallIntegerField(blank=True, null=True)),
                ('active_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asr_race_offense_subcat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('crime_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('crime_type_name', models.CharField(blank=True, max_length=50, null=True)),
                ('crime_type_sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('crime_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'crime_type',
            },
        ),
        migrations.CreateModel(
            name='CtArrestee',
            fields=[
                ('arrestee_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ct_arrestee',
            },
        ),
        migrations.CreateModel(
            name='CtIncident',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('incident_number', models.CharField(blank=True, max_length=15, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('source_flag', models.CharField(max_length=1)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('incident_hour', models.SmallIntegerField(blank=True, null=True)),
                ('cleared_except_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(max_length=1)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('unknown_offender', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_incident_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ct_incident',
            },
        ),
        migrations.CreateModel(
            name='CtMonth',
            fields=[
                ('ct_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('month_num', models.SmallIntegerField()),
                ('data_year', models.SmallIntegerField()),
                ('reported_status', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_count', models.IntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(max_length=1)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ct_month',
            },
        ),
        migrations.CreateModel(
            name='CtOffender',
            fields=[
                ('offender_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ct_offender',
            },
        ),
        migrations.CreateModel(
            name='CtOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ct_offense_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ct_offense',
            },
        ),
        migrations.CreateModel(
            name='CtProperty',
            fields=[
                ('property_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stolen_value', models.BigIntegerField(blank=True, null=True)),
                ('recovered_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('date_recovered', models.DateTimeField(blank=True, null=True)),
                ('recovered_value', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ct_property',
            },
        ),
        migrations.CreateModel(
            name='CtVictim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ct_victim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtWeapon',
            fields=[
                ('ct_weapon_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'ct_weapon',
            },
        ),
        migrations.CreateModel(
            name='HcBiasMotivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hc_bias_motivation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcIncident',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('incident_no', models.CharField(blank=True, max_length=20, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('source_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('adult_victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('incident_status', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('offender_count', models.SmallIntegerField(blank=True, null=True)),
                ('adult_offender_count', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_offender_count', models.SmallIntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_incident_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'hc_incident',
            },
        ),
        migrations.CreateModel(
            name='HcOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'hc_offense',
            },
        ),
        migrations.CreateModel(
            name='HcQuarter',
            fields=[
                ('quarter_num', models.SmallIntegerField()),
                ('data_year', models.SmallIntegerField()),
                ('reported_status', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_count', models.BigIntegerField(blank=True, null=True)),
                ('hc_quarter_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'hc_quarter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcVictim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hc_victim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HtMonth',
            fields=[
                ('ht_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('data_home', models.CharField(max_length=1)),
                ('source_flag', models.CharField(max_length=1)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('prepared_by_email', models.CharField(blank=True, max_length=200, null=True)),
                ('orig_format', models.CharField(max_length=1)),
                ('total_reported_count', models.IntegerField(blank=True, null=True)),
                ('total_unfounded_count', models.IntegerField(blank=True, null=True)),
                ('total_actual_count', models.IntegerField(blank=True, null=True)),
                ('total_cleared_count', models.IntegerField(blank=True, null=True)),
                ('total_juvenile_cleared_count', models.IntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ht_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HtMonthOffenseSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_count', models.IntegerField(blank=True, null=True)),
                ('reported_status', models.SmallIntegerField(blank=True, null=True)),
                ('unfounded_count', models.IntegerField(blank=True, null=True)),
                ('unfounded_status', models.SmallIntegerField(blank=True, null=True)),
                ('actual_count', models.IntegerField(blank=True, null=True)),
                ('actual_status', models.SmallIntegerField(blank=True, null=True)),
                ('cleared_count', models.IntegerField(blank=True, null=True)),
                ('cleared_status', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_cleared_count', models.IntegerField(blank=True, null=True)),
                ('juvenile_cleared_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ht_month_offense_subcat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsActivityType',
            fields=[
                ('activity_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('activity_type_code', models.CharField(blank=True, max_length=2, null=True)),
                ('activity_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_activity_type',
            },
        ),
        migrations.CreateModel(
            name='NibrsAge',
            fields=[
                ('age_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('age_code', models.CharField(blank=True, max_length=2, null=True)),
                ('age_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_age',
            },
        ),
        migrations.CreateModel(
            name='NibrsArrestee',
            fields=[
                ('arrestee_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('arrestee_seq_num', models.BigIntegerField(blank=True, null=True)),
                ('arrest_num', models.CharField(blank=True, max_length=12, null=True)),
                ('arrest_date', models.DateTimeField(blank=True, null=True)),
                ('multiple_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('resident_code', models.CharField(blank=True, max_length=1, null=True)),
                ('under_18_disposition_code', models.CharField(blank=True, max_length=1, null=True)),
                ('clearance_ind', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('age_range_low_num', models.SmallIntegerField(blank=True, null=True)),
                ('age_range_high_num', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_arrestee',
            },
        ),
        migrations.CreateModel(
            name='NibrsArresteeWeapon',
            fields=[
                ('nibrs_arrestee_weapon_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_arrestee_weapon',
            },
        ),
        migrations.CreateModel(
            name='NibrsArrestType',
            fields=[
                ('arrest_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('arrest_type_code', models.CharField(blank=True, max_length=1, null=True)),
                ('arrest_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_arrest_type',
            },
        ),
        migrations.CreateModel(
            name='NibrsAssignmentType',
            fields=[
                ('assignment_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('assignment_type_code', models.CharField(blank=True, max_length=1, null=True)),
                ('assignment_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_assignment_type',
            },
        ),
        migrations.CreateModel(
            name='NibrsBiasList',
            fields=[
                ('bias_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('bias_code', models.CharField(blank=True, max_length=2, null=True)),
                ('bias_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_bias_list',
            },
        ),
        migrations.CreateModel(
            name='NibrsBiasMotivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_bias_motivation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsCircumstances',
            fields=[
                ('circumstances_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('circumstances_type', models.CharField(blank=True, max_length=1, null=True)),
                ('circumstances_code', models.SmallIntegerField(blank=True, null=True)),
                ('circumstances_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_circumstances',
            },
        ),
        migrations.CreateModel(
            name='NibrsClearedExcept',
            fields=[
                ('cleared_except_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cleared_except_code', models.CharField(blank=True, max_length=1, null=True)),
                ('cleared_except_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_cleared_except',
            },
        ),
        migrations.CreateModel(
            name='NibrsCriminalAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_criminal_act',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsCriminalActType',
            fields=[
                ('criminal_act_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('criminal_act_code', models.CharField(blank=True, max_length=1, null=True)),
                ('criminal_act_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_criminal_act_type',
            },
        ),
        migrations.CreateModel(
            name='NibrsDrugMeasureType',
            fields=[
                ('drug_measure_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('drug_measure_code', models.CharField(blank=True, max_length=2, null=True)),
                ('drug_measure_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_drug_measure_type',
            },
        ),
        migrations.CreateModel(
            name='NibrsEds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('data_year', models.SmallIntegerField(blank=True, null=True)),
                ('month_num', models.SmallIntegerField(blank=True, null=True)),
                ('relative_rec_num', models.IntegerField(blank=True, null=True)),
                ('segment_action_type', models.CharField(blank=True, max_length=1, null=True)),
                ('ori', models.CharField(blank=True, max_length=9, null=True)),
                ('incident_num', models.CharField(blank=True, max_length=12, null=True)),
                ('level', models.CharField(blank=True, max_length=1, null=True)),
                ('offense_code', models.CharField(blank=True, max_length=3, null=True)),
                ('person_seq_num', models.CharField(blank=True, max_length=3, null=True)),
                ('type_prop_loss', models.CharField(blank=True, max_length=1, null=True)),
                ('data_element_num', models.CharField(blank=True, max_length=3, null=True)),
                ('error_num', models.SmallIntegerField(blank=True, null=True)),
                ('data_field', models.CharField(blank=True, max_length=12, null=True)),
                ('error_msg', models.CharField(blank=True, max_length=79, null=True)),
                ('submission_ser_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_eds',
            },
        ),
        migrations.CreateModel(
            name='NibrsEthnicity',
            fields=[
                ('ethnicity_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('ethnicity_code', models.CharField(blank=True, max_length=1, null=True)),
                ('ethnicity_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hc_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_ethnicity',
            },
        ),
        migrations.CreateModel(
            name='NibrsGrpbArrest',
            fields=[
                ('grpb_arrest_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('arrest_num', models.CharField(blank=True, max_length=15, null=True)),
                ('arrest_date', models.DateTimeField(blank=True, null=True)),
                ('arrest_seq_num', models.SmallIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=4, null=True)),
                ('arrest_type_id', models.SmallIntegerField(blank=True, null=True)),
                ('offense_type_id', models.BigIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('resident_code', models.CharField(blank=True, max_length=1, null=True)),
                ('under_18_disposition_code', models.CharField(blank=True, max_length=1, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('arrest_year', models.SmallIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('age_range_low_num', models.SmallIntegerField(blank=True, null=True)),
                ('age_range_high_num', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_grpb_arrest',
            },
        ),
        migrations.CreateModel(
            name='NibrsGrpbArrestWeapon',
            fields=[
                ('nibrs_grpb_arrest_weapon_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_grpb_arrest_weapon',
            },
        ),
        migrations.CreateModel(
            name='NibrsIncident',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('incident_number', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo_theft_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('report_date_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('incident_hour', models.SmallIntegerField(blank=True, null=True)),
                ('cleared_except_date', models.DateTimeField(blank=True, null=True)),
                ('incident_status', models.SmallIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_incident',
            },
        ),
        migrations.CreateModel(
            name='NibrsInjury',
            fields=[
                ('injury_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('injury_code', models.CharField(blank=True, max_length=1, null=True)),
                ('injury_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_injury',
            },
        ),
        migrations.CreateModel(
            name='NibrsJustifiableForce',
            fields=[
                ('justifiable_force_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('justifiable_force_code', models.CharField(blank=True, max_length=1, null=True)),
                ('justifiable_force_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_justifiable_force',
            },
        ),
        migrations.CreateModel(
            name='NibrsLocationType',
            fields=[
                ('location_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('location_code', models.CharField(blank=True, max_length=2, null=True)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_location_type',
            },
        ),
        migrations.CreateModel(
            name='NibrsMonth',
            fields=[
                ('nibrs_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('month_num', models.SmallIntegerField()),
                ('data_year', models.SmallIntegerField()),
                ('reported_status', models.CharField(blank=True, max_length=1, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('update_flag', models.CharField(max_length=1)),
                ('orig_format', models.CharField(max_length=1)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=50, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nibrs_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsOffender',
            fields=[
                ('offender_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offender_seq_num', models.SmallIntegerField(blank=True, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('age_range_low_num', models.SmallIntegerField(blank=True, null=True)),
                ('age_range_high_num', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_offender',
            },
        ),
        migrations.CreateModel(
            name='NibrsOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('attempt_complete_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('num_premises_entered', models.SmallIntegerField(blank=True, null=True)),
                ('method_entry_code', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_offense',
            },
        ),
        migrations.CreateModel(
            name='NibrsOffenseType',
            fields=[
                ('offense_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_code', models.CharField(blank=True, max_length=5, null=True)),
                ('offense_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crime_against', models.CharField(blank=True, max_length=100, null=True)),
                ('ct_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('hc_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('hc_code', models.CharField(blank=True, max_length=5, null=True)),
                ('offense_category_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_offense_type',
            },
        ),
        migrations.CreateModel(
            name='NibrsPropDescType',
            fields=[
                ('prop_desc_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('prop_desc_code', models.CharField(blank=True, max_length=2, null=True)),
                ('prop_desc_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_prop_desc_type',
            },
        ),
        migrations.CreateModel(
            name='NibrsProperty',
            fields=[
                ('property_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stolen_count', models.SmallIntegerField(blank=True, null=True)),
                ('recovered_count', models.SmallIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_property',
            },
        ),
        migrations.CreateModel(
            name='NibrsPropertyDesc',
            fields=[
                ('property_value', models.BigIntegerField(blank=True, null=True)),
                ('date_recovered', models.DateTimeField(blank=True, null=True)),
                ('nibrs_prop_desc_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_property_desc',
            },
        ),
        migrations.CreateModel(
            name='NibrsPropLossType',
            fields=[
                ('prop_loss_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('prop_loss_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_prop_loss_type',
            },
        ),
        migrations.CreateModel(
            name='NibrsRelationship',
            fields=[
                ('relationship_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('relationship_code', models.CharField(blank=True, max_length=2, null=True)),
                ('relationship_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_relationship',
            },
        ),
        migrations.CreateModel(
            name='NibrsSumMonthTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nibrs_month_id', models.BigIntegerField(blank=True, null=True)),
                ('agency_id', models.BigIntegerField(blank=True, null=True)),
                ('month_num', models.SmallIntegerField(blank=True, null=True)),
                ('data_year', models.SmallIntegerField(blank=True, null=True)),
                ('reported_status', models.CharField(blank=True, max_length=1, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=50, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_ct_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_hc_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_leoka_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_arson_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_ht_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_sum_month_temp',
            },
        ),
        migrations.CreateModel(
            name='NibrsSuspectedDrug',
            fields=[
                ('est_drug_qty', models.FloatField(blank=True, null=True)),
                ('nibrs_suspected_drug_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_suspected_drug',
            },
        ),
        migrations.CreateModel(
            name='NibrsSuspectedDrugType',
            fields=[
                ('suspected_drug_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('suspected_drug_code', models.CharField(blank=True, max_length=1, null=True)),
                ('suspected_drug_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_suspected_drug_type',
            },
        ),
        migrations.CreateModel(
            name='NibrsSuspectUsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_suspect_using',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsUsingList',
            fields=[
                ('suspect_using_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('suspect_using_code', models.CharField(blank=True, max_length=1, null=True)),
                ('suspect_using_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_using_list',
            },
        ),
        migrations.CreateModel(
            name='NibrsVictim',
            fields=[
                ('victim_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('victim_seq_num', models.SmallIntegerField(blank=True, null=True)),
                ('outside_agency_id', models.BigIntegerField(blank=True, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('resident_status_code', models.CharField(blank=True, max_length=1, null=True)),
                ('agency_data_year', models.SmallIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('age_range_low_num', models.SmallIntegerField(blank=True, null=True)),
                ('age_range_high_num', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_victim',
            },
        ),
        migrations.CreateModel(
            name='NibrsVictimCircumstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_victim_circumstances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsVictimInjury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_victim_injury',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsVictimOffenderRel',
            fields=[
                ('nibrs_victim_offender_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_victim_offender_rel',
            },
        ),
        migrations.CreateModel(
            name='NibrsVictimOffense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_victim_offense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsVictimType',
            fields=[
                ('victim_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('victim_type_code', models.CharField(blank=True, max_length=1, null=True)),
                ('victim_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_victim_type',
            },
        ),
        migrations.CreateModel(
            name='NibrsWeapon',
            fields=[
                ('nibrs_weapon_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_weapon',
            },
        ),
        migrations.CreateModel(
            name='NibrsWeaponType',
            fields=[
                ('weapon_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('weapon_code', models.CharField(blank=True, max_length=3, null=True)),
                ('weapon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shr_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'nibrs_weapon_type',
            },
        ),
        migrations.CreateModel(
            name='OffenseClassification',
            fields=[
                ('classification_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('classification_name', models.CharField(blank=True, max_length=50, null=True)),
                ('class_sort_order', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'offense_classification',
            },
        ),
        migrations.CreateModel(
            name='RefAgency',
            fields=[
                ('agency_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ori', models.CharField(max_length=9, unique=True)),
                ('legacy_ori', models.CharField(max_length=9)),
                ('ucr_agency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ncic_agency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pub_agency_name', models.CharField(blank=True, max_length=100, null=True)),
                ('special_mailing_group', models.CharField(blank=True, max_length=1, null=True)),
                ('special_mailing_address', models.CharField(blank=True, max_length=1, null=True)),
                ('agency_status', models.CharField(max_length=1)),
                ('judicial_dist_code', models.CharField(blank=True, max_length=4, null=True)),
                ('fid_code', models.CharField(blank=True, max_length=2, null=True)),
                ('added_date', models.DateTimeField(blank=True, null=True)),
                ('change_timestamp', models.DateTimeField(blank=True, null=True)),
                ('change_user', models.CharField(blank=True, max_length=100, null=True)),
                ('legacy_notify_agency', models.CharField(blank=True, max_length=1, null=True)),
                ('dormant_year', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_agency',
            },
        ),
        migrations.CreateModel(
            name='RefAgencyCounty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('core_city_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('data_year', models.SmallIntegerField()),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('census', models.BigIntegerField(blank=True, null=True)),
                ('legacy_county_code', models.CharField(blank=True, max_length=20, null=True)),
                ('legacy_msa_code', models.CharField(blank=True, max_length=20, null=True)),
                ('source_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('change_timestamp', models.DateTimeField(blank=True, null=True)),
                ('change_user', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ref_agency_county',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefAgencyCoveredBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'ref_agency_covered_by',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefAgencyDataContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.SmallIntegerField()),
                ('reporting_type', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_ct_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_hc_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_leoka_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_arson_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('summary_rape_def', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_ht_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'ref_agency_data_content',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefAgencyPoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.BigIntegerField()),
                ('primary_poc_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'ref_agency_poc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefAgencyType',
            fields=[
                ('agency_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('agency_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_agency_type',
            },
        ),
        migrations.CreateModel(
            name='RefCampusPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.SmallIntegerField()),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('source_flag', models.CharField(max_length=1)),
                ('census', models.BigIntegerField(blank=True, null=True)),
                ('change_timestamp', models.DateTimeField(blank=True, null=True)),
                ('change_user', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_population', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_campus_population',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefCity',
            fields=[
                ('city_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ref_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefContinent',
            fields=[
                ('continent_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('continent_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_continent',
            },
        ),
        migrations.CreateModel(
            name='RefCountry',
            fields=[
                ('country_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('country_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_country',
            },
        ),
        migrations.CreateModel(
            name='RefCounty',
            fields=[
                ('county_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('county_name', models.CharField(blank=True, max_length=100, null=True)),
                ('county_ansi_code', models.CharField(blank=True, max_length=5, null=True)),
                ('county_fips_code', models.CharField(blank=True, max_length=5, null=True)),
                ('legacy_county_code', models.CharField(blank=True, max_length=5, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_county',
            },
        ),
        migrations.CreateModel(
            name='RefCountyPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.SmallIntegerField()),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('source_flag', models.CharField(max_length=1)),
                ('change_timestamp', models.DateTimeField(blank=True, null=True)),
                ('change_user', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_population', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_county_population',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefDepartment',
            fields=[
                ('department_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('active_flag', models.CharField(max_length=1)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_department',
            },
        ),
        migrations.CreateModel(
            name='RefDivision',
            fields=[
                ('division_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('division_code', models.CharField(blank=True, max_length=2, null=True)),
                ('division_name', models.CharField(blank=True, max_length=100, null=True)),
                ('division_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_division',
            },
        ),
        migrations.CreateModel(
            name='RefFieldOffice',
            fields=[
                ('field_office_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('field_office_code', models.CharField(blank=True, max_length=10, null=True)),
                ('field_office_name', models.CharField(blank=True, max_length=100, null=True)),
                ('field_office_alpha_code', models.CharField(blank=True, max_length=2, null=True)),
                ('field_office_numeric_code', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_field_office',
            },
        ),
        migrations.CreateModel(
            name='RefGlobalLocation',
            fields=[
                ('global_location_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('global_location_desc', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_global_location',
            },
        ),
        migrations.CreateModel(
            name='RefMetroDivision',
            fields=[
                ('metro_div_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('metro_div_name', models.CharField(blank=True, max_length=100, null=True)),
                ('msa_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('metro_div_omb_code', models.CharField(blank=True, max_length=5, null=True)),
                ('legacy_msa_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_metro_division',
            },
        ),
        migrations.CreateModel(
            name='RefMetroDivPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.SmallIntegerField()),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('source_flag', models.CharField(max_length=1)),
                ('census', models.BigIntegerField(blank=True, null=True)),
                ('change_timestamp', models.DateTimeField(blank=True, null=True)),
                ('change_user', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_population', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_metro_div_population',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefMsa',
            fields=[
                ('msa_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('msa_name', models.CharField(blank=True, max_length=100, null=True)),
                ('msa_omb_code', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'ref_msa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefParentPopulationGroup',
            fields=[
                ('parent_pop_group_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parent_pop_group_code', models.CharField(blank=True, max_length=2, null=True)),
                ('parent_pop_group_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('publication_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_parent_population_group',
            },
        ),
        migrations.CreateModel(
            name='RefPoc',
            fields=[
                ('poc_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('poc_name', models.CharField(blank=True, max_length=200, null=True)),
                ('poc_title', models.CharField(blank=True, max_length=200, null=True)),
                ('poc_email', models.CharField(blank=True, max_length=200, null=True)),
                ('poc_phone1', models.CharField(blank=True, max_length=50, null=True)),
                ('poc_phone2', models.CharField(blank=True, max_length=50, null=True)),
                ('mailing_address_1', models.CharField(blank=True, max_length=150, null=True)),
                ('mailing_address_2', models.CharField(blank=True, max_length=150, null=True)),
                ('mailing_address_3', models.CharField(blank=True, max_length=150, null=True)),
                ('mailing_address_4', models.CharField(blank=True, max_length=150, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city_name', models.CharField(blank=True, max_length=100, null=True)),
                ('poc_fax1', models.CharField(blank=True, max_length=20, null=True)),
                ('poc_fax2', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_poc',
            },
        ),
        migrations.CreateModel(
            name='RefPocRole',
            fields=[
                ('poc_role_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('poc_role_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_poc_role',
            },
        ),
        migrations.CreateModel(
            name='RefPocRoleAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ref_poc_role_assign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefPopulationFamily',
            fields=[
                ('population_family_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('population_family_name', models.CharField(blank=True, max_length=100, null=True)),
                ('population_family_desc', models.CharField(blank=True, max_length=200, null=True)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_population_family',
            },
        ),
        migrations.CreateModel(
            name='RefPopulationGroup',
            fields=[
                ('population_group_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('population_group_code', models.CharField(blank=True, max_length=2, null=True)),
                ('population_group_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('publication_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_population_group',
            },
        ),
        migrations.CreateModel(
            name='RefRace',
            fields=[
                ('race_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('race_code', models.CharField(max_length=2, unique=True)),
                ('race_desc', models.CharField(max_length=100)),
                ('sort_order', models.SmallIntegerField(blank=True, null=True)),
                ('start_year', models.SmallIntegerField(blank=True, null=True)),
                ('end_year', models.SmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_race',
            },
        ),
        migrations.CreateModel(
            name='RefRegion',
            fields=[
                ('region_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('region_code', models.CharField(blank=True, max_length=2, null=True)),
                ('region_name', models.CharField(blank=True, max_length=100, null=True)),
                ('region_desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_region',
            },
        ),
        migrations.CreateModel(
            name='RefState',
            fields=[
                ('state_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
                ('state_abbr', models.CharField(blank=True, max_length=2, null=True)),
                ('state_postal_abbr', models.CharField(blank=True, max_length=2, null=True)),
                ('state_fips_code', models.CharField(blank=True, max_length=2, null=True)),
                ('state_pub_freq_months', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_state',
            },
        ),
        migrations.CreateModel(
            name='RefSubmittingAgency',
            fields=[
                ('agency_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sai', models.CharField(blank=True, max_length=9, null=True)),
                ('agency_name', models.CharField(blank=True, max_length=150, null=True)),
                ('notify_agency', models.CharField(blank=True, max_length=1, null=True)),
                ('agency_email', models.CharField(blank=True, max_length=200, null=True)),
                ('agency_website', models.CharField(blank=True, max_length=2000, null=True)),
                ('comments', models.CharField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_submitting_agency',
            },
        ),
        migrations.CreateModel(
            name='RefTribe',
            fields=[
                ('tribe_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tribe_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_tribe',
            },
        ),
        migrations.CreateModel(
            name='RefTribePopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_year', models.SmallIntegerField()),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('source_flag', models.CharField(max_length=1)),
                ('census', models.BigIntegerField(blank=True, null=True)),
                ('change_timestamp', models.DateTimeField(blank=True, null=True)),
                ('change_user', models.CharField(blank=True, max_length=100, null=True)),
                ('reporting_population', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ref_tribe_population',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefUniversity',
            fields=[
                ('university_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('university_abbr', models.CharField(blank=True, max_length=20, null=True)),
                ('university_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_university',
            },
        ),
        migrations.CreateModel(
            name='RefUniversityCampus',
            fields=[
                ('campus_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('campus_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'ref_university_campus',
            },
        ),
        migrations.CreateModel(
            name='RetaMonth',
            fields=[
                ('reta_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('data_home', models.CharField(max_length=1)),
                ('source_flag', models.CharField(max_length=1)),
                ('reported_flag', models.CharField(max_length=1)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('month_included_in', models.SmallIntegerField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('prepared_by_email', models.CharField(blank=True, max_length=200, null=True)),
                ('orig_format', models.CharField(max_length=1)),
                ('total_reported_count', models.IntegerField(blank=True, null=True)),
                ('total_unfounded_count', models.IntegerField(blank=True, null=True)),
                ('total_actual_count', models.IntegerField(blank=True, null=True)),
                ('total_cleared_count', models.IntegerField(blank=True, null=True)),
                ('total_juvenile_cleared_count', models.IntegerField(blank=True, null=True)),
                ('leoka_felony', models.SmallIntegerField(blank=True, null=True)),
                ('leoka_accident', models.SmallIntegerField(blank=True, null=True)),
                ('leoka_assault', models.IntegerField(blank=True, null=True)),
                ('leoka_status', models.SmallIntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reta_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetaMonthOffenseSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_count', models.IntegerField(blank=True, null=True)),
                ('reported_status', models.SmallIntegerField(blank=True, null=True)),
                ('unfounded_count', models.IntegerField(blank=True, null=True)),
                ('unfounded_status', models.SmallIntegerField(blank=True, null=True)),
                ('actual_count', models.IntegerField(blank=True, null=True)),
                ('actual_status', models.SmallIntegerField(blank=True, null=True)),
                ('cleared_count', models.IntegerField(blank=True, null=True)),
                ('cleared_status', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_cleared_count', models.IntegerField(blank=True, null=True)),
                ('juvenile_cleared_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reta_month_offense_subcat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetaOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_name', models.CharField(max_length=100)),
                ('offense_code', models.CharField(max_length=20, unique=True)),
                ('offense_xml_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('offense_sort_order', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'reta_offense',
            },
        ),
        migrations.CreateModel(
            name='RetaOffenseCategory',
            fields=[
                ('offense_category_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('offense_category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('offense_category_sort_order', models.SmallIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'reta_offense_category',
            },
        ),
        migrations.CreateModel(
            name='RetaOffenseSubcat',
            fields=[
                ('offense_subcat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_subcat_name', models.CharField(max_length=100)),
                ('offense_subcat_code', models.CharField(max_length=20, unique=True)),
                ('offense_subcat_xml_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('offense_subcat_sort_order', models.BigIntegerField(blank=True, null=True)),
                ('part', models.CharField(blank=True, max_length=1, null=True)),
                ('crime_index_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'reta_offense_subcat',
            },
        ),
        migrations.CreateModel(
            name='ShrCircumstances',
            fields=[
                ('circumstances_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('circumstances_code', models.CharField(max_length=2)),
                ('sub_code', models.CharField(blank=True, max_length=1, null=True)),
                ('circumstances_name', models.CharField(max_length=100)),
                ('sub_name', models.CharField(blank=True, max_length=100, null=True)),
                ('current_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'shr_circumstances',
            },
        ),
        migrations.CreateModel(
            name='ShrIncident',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('homicide_code', models.CharField(blank=True, max_length=1, null=True)),
                ('incident_num', models.CharField(blank=True, max_length=3, null=True)),
                ('incident_status', models.SmallIntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_incident_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shr_incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShrMonth',
            fields=[
                ('shr_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('data_home', models.CharField(max_length=1)),
                ('source_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shr_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShrOffender',
            fields=[
                ('offender_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offender_num', models.CharField(blank=True, max_length=20, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_offender_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'shr_offender',
            },
        ),
        migrations.CreateModel(
            name='ShrOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'shr_offense',
            },
        ),
        migrations.CreateModel(
            name='ShrRelationship',
            fields=[
                ('relationship_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('relationship_code', models.CharField(blank=True, max_length=2, null=True)),
                ('relationship_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'shr_relationship',
            },
        ),
        migrations.CreateModel(
            name='ShrSituation',
            fields=[
                ('situation_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('situation_code', models.CharField(blank=True, max_length=1, null=True)),
                ('situation_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'shr_situation',
            },
        ),
        migrations.CreateModel(
            name='ShrVictim',
            fields=[
                ('victim_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('victim_num', models.CharField(blank=True, max_length=20, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_victim_id', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'shr_victim',
            },
        ),
        migrations.CreateModel(
            name='SuppLarcenyType',
            fields=[
                ('larceny_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('larceny_type_name', models.CharField(max_length=100)),
                ('larceny_type_code', models.CharField(max_length=20)),
                ('larceny_xml_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'supp_larceny_type',
            },
        ),
        migrations.CreateModel(
            name='SuppMonth',
            fields=[
                ('supp_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('data_home', models.CharField(max_length=1)),
                ('source_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_flag', models.CharField(max_length=1)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('orig_format', models.CharField(max_length=1)),
                ('mv_stolen_local_rec_local', models.BigIntegerField(blank=True, null=True)),
                ('mv_stolen_local_rec_other', models.BigIntegerField(blank=True, null=True)),
                ('mv_tot_local_stolen_rec', models.BigIntegerField(blank=True, null=True)),
                ('mv_stolen_other_rec_local', models.BigIntegerField(blank=True, null=True)),
                ('mv_stolen_status', models.SmallIntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supp_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuppOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_name', models.CharField(max_length=100)),
                ('offense_code', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'supp_offense',
            },
        ),
        migrations.CreateModel(
            name='SuppOffenseSubcat',
            fields=[
                ('offense_subcat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_subcat_name', models.CharField(max_length=100)),
                ('offense_subcat_code', models.CharField(max_length=20)),
                ('offense_subcat_xml_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'supp_offense_subcat',
            },
        ),
        migrations.CreateModel(
            name='SuppPropByOffenseSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_count', models.IntegerField(blank=True, null=True)),
                ('actual_status', models.SmallIntegerField(blank=True, null=True)),
                ('stolen_value', models.BigIntegerField(blank=True, null=True)),
                ('stolen_value_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supp_prop_by_offense_subcat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuppPropertyByTypeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stolen_value', models.BigIntegerField(blank=True, null=True)),
                ('stolen_value_status', models.SmallIntegerField(blank=True, null=True)),
                ('recovered_value', models.BigIntegerField(blank=True, null=True)),
                ('recovered_value_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supp_property_by_type_value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SuppPropertyType',
            fields=[
                ('prop_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('prop_type_name', models.CharField(max_length=100)),
                ('prop_type_code', models.CharField(max_length=20)),
                ('prop_type_code_num', models.SmallIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'supp_property_type',
            },
        ),
        migrations.CreateModel(
            name='AsrJuvenileDisposition',
            fields=[
                ('asr_month', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='crime_data_api.AsrMonth')),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('handled_within_dept', models.IntegerField(blank=True, null=True)),
                ('juvenile_court', models.IntegerField(blank=True, null=True)),
                ('welfare_agency', models.IntegerField(blank=True, null=True)),
                ('other_police', models.IntegerField(blank=True, null=True)),
                ('adult_court', models.IntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'asr_juvenile_disposition',
            },
        ),
    ]
