set colsep ,     
set pagesize 0   
set trimspool on 
set headsep on  
set linesize 4096   
set numw 10     
SET TERMOUT OFF 
SET ECHO OFF 

SPOOL ArsonMBS.csv

select AMBS.ARSON_MONTH_ID, AMBS.SUBCATEGORY_ID, AMBS.REPORTED_COUNT, AMBS.REPORTED_STATUS, AMBS.UNFOUNDED_COUNT, AMBS.UNFOUNDED_STATUS,   AMBS.ACTUAL_COUNT,  AMBS.ACTUAL_STATUS, AMBS.CLEARED_COUNT,  AMBS.CLEARED_STATUS, AMBS.JUVENILE_CLEARED_COUNT, AMBS.JUVENILE_CLEARED_STATUS, AMBS.UNINHABITED_COUNT, AMBS.UNINHABITED_STATUS, AMBS.EST_DAMAGE_VALUE, AMBS.EST_DAMAGE_VALUE_STATUS from ARSON_MONTH AM  JOIN ARSON_MONTH_BY_SUBCAT AMBS ON AM.ARSON_MONTH_ID = AMBS.ARSON_MONTH_ID WHERE AM.DATA_YEAR = 2016;

SPOOL OFF

SPOOL ArsonM.csv

select AM.ARSON_MONTH_ID, AM.AGENCY_ID, AM.DATA_YEAR, AM.MONTH_NUM, AM.DATA_HOME, AM.SOURCE_FLAG, AM.REPORTED_FLAG, AM.DDOCNAME, AM.MONTH_INCLUDED_IN, AM.REPORT_DATE, AM.PREPARED_DATE, AM.ORIG_FORMAT, AM.UPDATE_FLAG, AM.DID, AM.FF_LINE_NUMBER, AM.MONTH_PUB_STATUS from ARSON_MONTH AM WHERE AM.DATA_YEAR = 2016;

SPOOL OFF


END_SQL
EXIT