set colsep ,     
set pagesize 0   
set trimspool on 
set headsep on  
set linesize 4096   
set numw 10     
SET TERMOUT OFF 
SET ECHO OFF 

SPOOL ASRM.csv

select ASR_MONTH_ID,AGENCY_ID, DATA_YEAR, MONTH_NUM, SOURCE_FLAG, REPORTED_FLAG, ORIG_FORMAT, UPDATE_FLAG, FF_LINE_NUMBER, DDOCNAME, DID, DATA_HOME, MONTH_PUB_STATUS from ASR_MONTH AM WHERE AM.DATA_YEAR = 2016;

SPOOL OFF


SPOOL ASRASS.csv

select ASR_MONTH_ID,  OFFENSE_SUBCAT_ID, AGE_RANGE_ID,  ARREST_COUNT,  ARREST_STATUS, ACTIVE_FLAG PREPARED_DATE, REPORT_DATE, FF_LINE_NUMBER from ASR_AGE_SEX_SUBCAT AASS JOIN ASR_MONTH AM ON AM.ASR_MONTH_ID = AASS.ASR_MONTH_ID WHERE AM.DATA_YEAR = 2016;

SPOOL OFF


SPOOL ASRROS.csv

select ASR_MONTH_ID, OFFENSE_SUBCAT_ID, RACE_ID, JUVENILE_FLAG, ARREST_COUNT, ARREST_STATUS, ACTIVE_FLAG, PREPARED_DATE, REPORT_DATE, FF_LINE_NUMBER from ASR_RACE_OFFENSE_SUBCAT AROS JOIN ASR_MONTH AM ON AM.ASR_MONTH_ID = AROS.ASR_MONTH_ID WHERE AM.DATA_YEAR = 2016;

SPOOL OFF

END_SQL
EXIT