set colsep ,     
set pagesize 0   
set trimspool on 
set headsep on  
set linesize 4096   
set numw 10     
SET TERMOUT OFF 
SET ECHO OFF 

SPOOL LKAABA.csv

select LABA.LKASUM_MONTH_ID, LABA.ACTIVITY_ID, LABA.ASSIGNMENT_ID, LABA.ACTUAL_COUNT, LABA.ACTUAL_STATUS from LKASUM_MONTH LM  JOIN LKASUM_ASSAULT_BY_ASSIGNMENT LABA ON LM.LKASUM_MONTH_ID = LABA.LKASUM_MONTH_ID WHERE LM.DATA_YEAR = 2016;

SPOOL OFF

SPOOL LKAABW.csv

select LABW.LKASUM_MONTH_ID, LABW.ACTIVITY_ID, LABW.WEAPON_ID, LABW.ACTUAL_COUNT, LABW.ACTUAL_STATUS from LKASUM_MONTH LM  JOIN LKASUM_ASSAULT_BY_WEAPON LABW ON LM.LKASUM_MONTH_ID = LABW.LKASUM_MONTH_ID WHERE LM.DATA_YEAR = 2016;

SPOOL OFF

SPOOL LKAAT.csv

select LAT.LKASUM_MONTH_ID, LAT.TIME_RANGE_ID, LAT.ACTUAL_COUNT, LAT.ACTUAL_STATUS from LKASUM_MONTH LM  JOIN LKASUM_ASSAULT_TIME LAT ON LM.LKASUM_MONTH_ID = LAT.LKASUM_MONTH_ID WHERE LM.DATA_YEAR = 2016;

SPOOL OFF

SPOOL LKAC.csv

select LC.LKASUM_MONTH_ID, LC.ACTIVITY_ID, LC.CLEARED_COUNT, LC.CLEARED_STATUS from LKASUM_MONTH LM  JOIN LKASUM_CLEARED LC ON LM.LKASUM_MONTH_ID = LC.LKASUM_MONTH_ID WHERE LM.DATA_YEAR = 2016;

SPOOL OFF

SPOOL LKAI.csv

select LI.LKASUM_MONTH_ID, LI.WEAPON_ID, LI.INJURY_COUNT, LI.INJURY_STATUS, LI.NO_INJURY_COUNT, LI.NO_INJURY_STATUS from LKASUM_MONTH LM  JOIN LKASUM_INJURY LI ON LM.LKASUM_MONTH_ID = LI.LKASUM_MONTH_ID WHERE LM.DATA_YEAR = 2016;

SPOOL OFF

SPOOL LKAM.csv

select LM.LKASUM_MONTH_ID, LM.AGENCY_ID, LM.DATA_YEAR, LM.MONTH_NUM, LM.DATA_HOME, LM.SOURCE_FLAG, LM.REPORT_DATE, LM.PREPARED_DATE, LM.REPORTED_FLAG, LM.DDOCNAME, LM.LEOKA_FELONY, LM.LEOKA_ACCIDENT, LM.ORIG_FORMAT, LM.UPDATE_FLAG, LM.DID, LM.FF_LINE_NUMBER, LM.MONTH_PUB_STATUS, LM.REPORTING_RANK from LKASUM_MONTH LM WHERE LM.DATA_YEAR = 2016;

SPOOL OFF


END_SQL
EXIT