set colsep ,     
set pagesize 0   
set trimspool on 
set headsep on  
set linesize 4096   
set numw 10     
SET TERMOUT OFF 
SET ECHO OFF 

SPOOL NM.csv
select NIBRS_MONTH_ID, AGENCY_ID, MONTH_NUM, DATA_YEAR, REPORTED_STATUS, REPORT_DATE, PREPARED_DATE, UPDATE_FLAG, ORIG_FORMAT, FF_LINE_NUMBER, DATA_HOME, DDOCNAME, DID from NIBRS_MONTH NM WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NI.csv
select NI.AGENCY_ID, NI.INCIDENT_ID, NI.NIBRS_MONTH_ID, NI.INCIDENT_NUMBER, NI.CARGO_THEFT_FLAG, NI.SUBMISSION_DATE, NI.INCIDENT_DATE, NI.REPORT_DATE_FLAG, NI.INCIDENT_HOUR, NI.CLEARED_EXCEPT_ID, NI.CLEARED_EXCEPT_DATE, NI.INCIDENT_STATUS, NI.DATA_HOME, NI.DDOCNAME, NI.ORIG_FORMAT, NI.FF_LINE_NUMBER, NI.DID from nibrs_incident NI JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NOFF.csv
select NOFF.OFFENSE_ID, NOFF.INCIDENT_ID, NOFF.OFFENSE_TYPE_ID, NOFF.ATTEMPT_COMPLETE_FLAG, NOFF.LOCATION_ID, NOFF.NUM_PREMISES_ENTERED, NOFF.METHOD_ENTRY_CODE, NOFF.FF_LINE_NUMBER FROM nibrs_offense NOFF JOIN nibrs_incident NI ON NI.INCIDENT_ID = NOFF.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NSU.csv
select NSU.SUSPECT_USING_ID, NSU.OFFENSE_ID from nibrs_suspect_using NSU JOIN nibrs_offense NOFF ON NSU.OFFENSE_ID = NOFF.OFFENSE_ID JOIN nibrs_incident NI ON NI.INCIDENT_ID = NOFF.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NBM.csv
select NBM.BIAS_ID, NBM.OFFENSE_ID FROM nibrs_bias_motivation NBM JOIN  nibrs_offense NOFF ON NOFF.OFFENSE_ID = NBM.OFFENSE_ID  JOIN nibrs_incident NI ON NI.INCIDENT_ID = NOFF.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NCA.csv
select NCA.CRIMINAL_ACT_ID, NCA.OFFENSE_ID from nibrs_criminal_act NCA JOIN  nibrs_offense NOFF ON NOFF.OFFENSE_ID = NCA.OFFENSE_ID  JOIN nibrs_incident NI ON NI.INCIDENT_ID = NOFF.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NW.csv
select NW.WEAPON_ID, NW.OFFENSE_ID, NW.NIBRS_WEAPON_ID from Nibrs_weapon NW JOIN  nibrs_offense NOFF ON NOFF.OFFENSE_ID = NW.OFFENSE_ID  JOIN nibrs_incident NI ON NI.INCIDENT_ID = NOFF.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NP.csv
select NP.PROPERTY_ID, NP.INCIDENT_ID, NP.PROP_LOSS_ID, NP.STOLEN_COUNT, NP.RECOVERED_COUNT, NP.FF_LINE_NUMBER FROM nibrs_property NP JOIN nibrs_incident NI ON NP.INCIDENT_ID = NI.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NPD.csv
select NPD.PROPERTY_ID, NPD.PROP_DESC_ID, NPD.PROPERTY_VALUE, NPD.DATE_RECOVERED, NPD.NIBRS_PROP_DESC_ID from nibrs_property_desc NPD JOIN nibrs_property NP ON NP.PROPERTY_ID = NPD.PROPERTY_ID JOIN nibrs_incident NI ON NP.INCIDENT_ID = NI.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NSD.csv
select NSD.SUSPECTED_DRUG_TYPE_ID, NSD.PROPERTY_ID, NSD.EST_DRUG_QTY, NSD.DRUG_MEASURE_TYPE_ID, NSD.NIBRS_SUSPECTED_DRUG_ID FROM nibrs_suspected_drug NSD JOIN nibrs_property NP ON NP.PROPERTY_ID = NSD.PROPERTY_ID JOIN nibrs_incident NI ON NP.INCIDENT_ID = NI.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NOF.csv
select NOF.OFFENDER_ID, NOF.INCIDENT_ID, NOF.OFFENDER_SEQ_NUM, NOF.AGE_ID, NOF.AGE_NUM, NOF.SEX_CODE, NOF.RACE_ID, NOF.ETHNICITY_ID, NOF.FF_LINE_NUMBER, NOF.AGE_RANGE_LOW_NUM, NOF.AGE_RANGE_HIGH_NUM FROM nibrs_offender NOF JOIN nibrs_incident NI ON NOF.INCIDENT_ID = NI.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NA.csv
select NA.ARRESTEE_ID, NA.INCIDENT_ID, NA.ARRESTEE_SEQ_NUM, NA.ARREST_NUM, NA.ARREST_DATE, NA.ARREST_TYPE_ID, NA.MULTIPLE_INDICATOR, NA.OFFENSE_TYPE_ID, NA.AGE_ID, NA.AGE_NUM, NA.SEX_CODE, NA.RACE_ID, NA.ETHNICITY_ID, NA.RESIDENT_CODE, NA.UNDER_18_DISPOSITION_CODE, NA.CLEARANCE_IND, NA.FF_LINE_NUMBER, NA.AGE_RANGE_LOW_NUM, NA.AGE_RANGE_HIGH_NUM FROM nibrs_arrestee NA JOIN nibrs_incident NI ON NA.INCIDENT_ID = NI.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NAW.csv
select NAW.ARRESTEE_ID, NAW.WEAPON_ID, NAW.NIBRS_ARRESTEE_WEAPON_ID FROM nibrs_arrestee_weapon NAW JOIN nibrs_arrestee NA ON NAW.ARRESTEE_ID = NA.ARRESTEE_ID JOIN nibrs_incident NI ON NA.INCIDENT_ID = NI.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NV.csv
select NV.VICTIM_ID, NV.INCIDENT_ID, NV.VICTIM_SEQ_NUM, NV.VICTIM_TYPE_ID, NV.ASSIGNMENT_TYPE_ID, NV.ACTIVITY_TYPE_ID, NV.OUTSIDE_AGENCY_ID, NV.AGE_ID, NV.AGE_NUM, NV.SEX_CODE, NV.RACE_ID, NV.ETHNICITY_ID, NV.RESIDENT_STATUS_CODE, NV.AGENCY_DATA_YEAR, NV.FF_LINE_NUMBER, NV.AGE_RANGE_LOW_NUM, NV.AGE_RANGE_HIGH_NUM FROM nibrs_victim NV JOIN nibrs_incident NI ON NV.INCIDENT_ID = NI.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NVC.csv
select NVC.VICTIM_ID, NVC.CIRCUMSTANCES_ID, NVC.JUSTIFIABLE_FORCE_ID FROM nibrs_victim_circumstances NVC JOIN nibrs_victim NV ON NV.VICTIM_ID = NVC.VICTIM_ID JOIN nibrs_incident NI ON NV.INCIDENT_ID = NI.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NVI.csv
select NVI.VICTIM_ID,  NVI.INJURY_ID FROM NIBRS_VICTIM_INJURY NVI JOIN nibrs_victim NV ON NV.VICTIM_ID = NVI.VICTIM_ID JOIN nibrs_incident NI ON NV.INCIDENT_ID = NI.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NVO.csv
select NVO.VICTIM_ID, NVO.OFFENSE_ID FROM nibrs_victim_offense NVO JOIN nibrs_victim NV ON NV.VICTIM_ID = NVO.VICTIM_ID JOIN nibrs_incident NI ON NV.INCIDENT_ID = NI.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

SPOOL NVOR.csv
select NVOR.VICTIM_ID, NVOR.OFFENDER_ID, NVOR.RELATIONSHIP_ID, NVOR.NIBRS_VICTIM_OFFENDER_ID FROM nibrs_victim_offender_rel NVOR JOIN nibrs_victim NV ON NV.VICTIM_ID = NVOR.VICTIM_ID JOIN nibrs_incident NI ON NV.INCIDENT_ID = NI.INCIDENT_ID JOIN NIBRS_MONTH NM ON NI.NIBRS_MONTH_ID = NM.NIBRS_MONTH_ID WHERE DATA_YEAR = 2016;
SPOOL OFF

END_SQL
EXIT
