set colsep |     
set pagesize 0   
set trimspool on 
set headsep on  
set linesize 4096   
set numw 10     
SET TERMOUT OFF 
SET ECHO OFF 

SPOOL REFA.csv
select RA.AGENCY_ID, RA.ORI, RA.LEGACY_ORI,  RA.UCR_AGENCY_NAME, RA.NCIC_AGENCY_NAME,  RA.PUB_AGENCY_NAME, RA.AGENCY_TYPE_ID,  RA.SPECIAL_MAILING_GROUP, RA.SPECIAL_MAILING_ADDRESS, RA.TRIBE_ID,  RA.CITY_ID, RA.STATE_ID,  RA.CAMPUS_ID, RA.AGENCY_STATUS, RA.JUDICIAL_DIST_CODE, RA.SUBMITTING_AGENCY_ID,  RA.FID_CODE,  RA.DEPARTMENT_ID, RA.ADDED_DATE, RA.CHANGE_TIMESTAMP,  RA.CHANGE_USER, RA.LEGACY_NOTIFY_AGENCY,  RA.DORMANT_YEAR,  RA.POPULATION_FAMILY_ID,  RA.FIELD_OFFICE_ID, RA.PUB_AGENCY_UNIT from ref_agency RA;
SPOOL OFF
SPOOL REFAC.csv
select AGENCY_ID, COUNTY_ID, METRO_DIV_ID,  CORE_CITY_FLAG,  DATA_YEAR, POPULATION,  CENSUS,  LEGACY_COUNTY_CODE,  LEGACY_MSA_CODE, SOURCE_FLAG, CHANGE_TIMESTAMP, CHANGE_USER from ref_agency_county;
SPOOL OFF
SPOOL REFACB.csv
select AGENCY_ID, DATA_YEAR, COVERED_BY_AGENCY_ID from ref_agency_covered_by;
SPOOL OFF
SPOOL REFAP.csv
select AGENCY_ID, DATA_YEAR, POPULATION_GROUP_ID, POPULATION, SOURCE_FLAG, CHANGE_TIMESTAMP, CHANGE_USER, CITY_SEQUENCE, SUBURBAN_AREA_FLAG from ref_agency_population;
SPOOL OFF
SPOOL REFCP.csv
select CAMPUS_ID, DATA_YEAR, POPULATION, SOURCE_FLAG, CENSUS, CHANGE_TIMESTAMP, CHANGE_USER, REPORTING_POPULATION from REF_CAMPUS_POPULATION;
SPOOL OFF
SPOOL REFTP.csv
select TRIBE_ID, DATA_YEAR, POPULATION, SOURCE_FLAG, CENSUS, CHANGE_TIMESTAMP, CHANGE_USER, REPORTING_POPULATION from Ref_tribe_population;
SPOOL OFF
SPOOL REFC.csv
select COUNTY_ID, STATE_ID, COUNTY_NAME, COUNTY_ANSI_CODE, COUNTY_FIPS_CODE, LEGACY_COUNTY_CODE, COMMENTS from Ref_county;
SPOOL OFF
SPOOL REFCY.csv
select CITY_ID, STATE_ID, CITY_NAME from Ref_city;
SPOOL OFF


END_SQL
EXIT