set colsep ,     
set pagesize 0   
set trimspool on 
set headsep on  
set linesize 4096   
set numw 10     
SET TERMOUT OFF 
SET ECHO OFF 

SPOOL RETAMOS.csv

select RMOS.RETA_MONTH_ID, RMOS.OFFENSE_SUBCAT_ID, RMOS.REPORTED_COUNT, RMOS.REPORTED_STATUS, RMOS.UNFOUNDED_COUNT, RMOS.UNFOUNDED_STATUS,  RMOS.ACTUAL_COUNT,  RMOS.ACTUAL_STATUS, RMOS.CLEARED_COUNT, RMOS.CLEARED_STATUS,  RMOS.JUVENILE_CLEARED_COUNT,  RMOS.JUVENILE_CLEARED_STATUS from RETA_MONTH RM  JOIN RETA_MONTH_OFFENSE_SUBCAT RMOS ON RM.RETA_MONTH_ID = RMOS.RETA_MONTH_ID WHERE RM.DATA_YEAR = 2016;

SPOOL OFF

SPOOL RETAM.csv

select RETA_MONTH_ID, AGENCY_ID, DATA_YEAR, MONTH_NUM, DATA_HOME, SOURCE_FLAG, REPORTED_FLAG, DDOCNAME,  MONTH_INCLUDED_IN, REPORT_DATE, PREPARED_DATE, PREPARED_BY_USER,  PREPARED_BY_EMAIL, ORIG_FORMAT, LEOKA_FELONY,  LEOKA_ACCIDENT,  LEOKA_ASSAULT, LEOKA_STATUS,  UPDATE_FLAG, DID, FF_LINE_NUMBER, MONTH_PUB_STATUS from RETA_MONTH RM WHERE RM.DATA_YEAR = 2016;

SPOOL OFF


END_SQL
EXIT
