# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ref', '0001_initial'),
        ('nibrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtArrestee',
            fields=[
                ('arrestee_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsEthnicity')),
            ],
            options={
                'db_table': 'ct_arrestee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CtIncident',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('incident_number', models.CharField(blank=True, max_length=15, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('source_flag', models.CharField(max_length=1)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('incident_hour', models.SmallIntegerField(blank=True, null=True)),
                ('cleared_except_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(max_length=1)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('unknown_offender', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_incident_id', models.BigIntegerField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefAgency')),
            ],
            options={
                'db_table': 'ct_incident',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CtMonth',
            fields=[
                ('ct_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('month_num', models.SmallIntegerField()),
                ('data_year', models.SmallIntegerField()),
                ('reported_status', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_count', models.IntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(max_length=1)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefAgency')),
            ],
            options={
                'db_table': 'ct_month',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CtOffender',
            fields=[
                ('offender_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('ethnicity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsEthnicity')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ct.CtIncident')),
                ('race', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefRace')),
            ],
            options={
                'db_table': 'ct_offender',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CtOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ct_offense_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ct.CtIncident')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsLocationType')),
                ('offense_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsOffenseType')),
            ],
            options={
                'db_table': 'ct_offense',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CtProperty',
            fields=[
                ('property_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stolen_value', models.BigIntegerField(blank=True, null=True)),
                ('recovered_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('date_recovered', models.DateTimeField(blank=True, null=True)),
                ('recovered_value', models.BigIntegerField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ct.CtIncident')),
                ('prop_desc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsPropDescType')),
            ],
            options={
                'db_table': 'ct_property',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CtVictim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ct.CtIncident')),
                ('victim_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsVictimType')),
            ],
            options={
                'db_table': 'ct_victim',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CtWeapon',
            fields=[
                ('ct_weapon_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ct.CtIncident')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsWeaponType')),
            ],
            options={
                'db_table': 'ct_weapon',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ctincident',
            name='ct_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ct.CtMonth'),
        ),
        migrations.AddField(
            model_name='ctarrestee',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ct.CtIncident'),
        ),
        migrations.AddField(
            model_name='ctarrestee',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefRace'),
        ),
        migrations.AlterUniqueTogether(
            name='ctvictim',
            unique_together=set([('incident', 'victim_type')]),
        ),
    ]
