# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtArrestee',
            fields=[
                ('arrestee_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'ct_arrestee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtIncident',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('incident_number', models.CharField(blank=True, max_length=15, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('source_flag', models.CharField(max_length=1)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('incident_hour', models.SmallIntegerField(blank=True, null=True)),
                ('cleared_except_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(max_length=1)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('unknown_offender', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_incident_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ct_incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtMonth',
            fields=[
                ('ct_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('month_num', models.SmallIntegerField()),
                ('data_year', models.SmallIntegerField()),
                ('reported_status', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_count', models.IntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(max_length=1)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'ct_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtOffender',
            fields=[
                ('offender_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'ct_offender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ct_offense_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'ct_offense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtProperty',
            fields=[
                ('property_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stolen_value', models.BigIntegerField(blank=True, null=True)),
                ('recovered_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('date_recovered', models.DateTimeField(blank=True, null=True)),
                ('recovered_value', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ct_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtVictim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ct_victim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtWeapon',
            fields=[
                ('ct_weapon_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ct_weapon',
                'managed': False,
            },
        ),
    ]
