# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArsonMonth',
            fields=[
                ('arson_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('data_home', models.CharField(max_length=1)),
                ('source_flag', models.CharField(max_length=1)),
                ('reported_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('month_included_in', models.SmallIntegerField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arson_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArsonMonthBySubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_count', models.IntegerField(blank=True, null=True)),
                ('reported_status', models.SmallIntegerField(blank=True, null=True)),
                ('unfounded_count', models.IntegerField(blank=True, null=True)),
                ('unfounded_status', models.SmallIntegerField(blank=True, null=True)),
                ('actual_count', models.IntegerField(blank=True, null=True)),
                ('actual_status', models.SmallIntegerField(blank=True, null=True)),
                ('cleared_count', models.IntegerField(blank=True, null=True)),
                ('cleared_status', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_cleared_count', models.IntegerField(blank=True, null=True)),
                ('juvenile_cleared_status', models.SmallIntegerField(blank=True, null=True)),
                ('uninhabited_count', models.IntegerField(blank=True, null=True)),
                ('uninhabited_status', models.SmallIntegerField(blank=True, null=True)),
                ('est_damage_value', models.BigIntegerField(blank=True, null=True)),
                ('est_damage_value_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arson_month_by_subcat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArsonSubcategory',
            fields=[
                ('subcategory_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('subcategory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subcategory_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('subcat_xml_path', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'arson_subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArsonSubclassification',
            fields=[
                ('subclass_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('subclass_name', models.CharField(blank=True, max_length=100, null=True)),
                ('subclass_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('subclass_xml_path', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'arson_subclassification',
                'managed': False,
            },
        ),
    ]
