-- REFRESHs
REFRESH MATERIALIZED VIEW public.leoka_assault_by_group_regional_totals;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_group_state_totals;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_group_national;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_group_regional;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_group_state;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_assign_dist_national;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_assign_dist_regional;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_assign_dist_state;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_assign_dist_agency;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_weapon_national;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_weapon_regional;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_weapon_state;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_weapon_agency;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_weapon_per_group_national;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_weapon_per_group_regional;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_weapon_per_group_state;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_weapon_per_activity_national;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_weapon_per_activity_regional;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_weapon_per_activity_state;
REFRESH MATERIALIZED VIEW public.leoka_assault_by_weapon_per_activity_agency;

REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_offender_age;
REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_offender_ethnicity;
REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_offender_race;
REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_offender_count;
REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_offender_sex;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_offender_age;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_offender_ethnicity;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_offender_race;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_offender_count;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_offender_sex;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_offender_age;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_offender_ethnicity;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_offender_race;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_offender_count;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_offender_sex;


REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_offense_count;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_offense_count;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_offense_count;

REFRESH MATERIALIZED VIEW public.police_employment_agency
REFRESH MATERIALIZED VIEW public.police_employment_state
REFRESH MATERIALIZED VIEW public.police_employment_region
REFRESH MATERIALIZED VIEW public.police_employment_nation


REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_victim_location;
REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_victim_age;
REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_victim_ethnicity;
REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_victim_race;
REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_victim_count;
REFRESH MATERIALIZED VIEW public.nibrs_agency_denorm_victim_sex;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_victim_location;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_victim_age;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_victim_ethnicity;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_victim_race;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_victim_count;
REFRESH MATERIALIZED VIEW public.nibrs_state_denorm_victim_sex;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_victim_location;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_victim_age;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_victim_ethnicity;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_victim_race;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_victim_count;
REFRESH MATERIALIZED VIEW public.nibrs_national_denorm_victim_sex;

REFRESH MATERIALIZED VIEW nibrs_agency_denorm_victim_offender_relationship;
REFRESH MATERIALIZED VIEW nibrs_state_denorm_victim_offender_relationship;
REFRESH MATERIALIZED VIEW nibrs_national_denorm_victim_offender_relationship;
