# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetaMonth',
            fields=[
                ('reta_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('data_home', models.CharField(max_length=1)),
                ('source_flag', models.CharField(max_length=1)),
                ('reported_flag', models.CharField(max_length=1)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('month_included_in', models.SmallIntegerField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('prepared_by_email', models.CharField(blank=True, max_length=200, null=True)),
                ('orig_format', models.CharField(max_length=1)),
                ('total_reported_count', models.IntegerField(blank=True, null=True)),
                ('total_unfounded_count', models.IntegerField(blank=True, null=True)),
                ('total_actual_count', models.IntegerField(blank=True, null=True)),
                ('total_cleared_count', models.IntegerField(blank=True, null=True)),
                ('total_juvenile_cleared_count', models.IntegerField(blank=True, null=True)),
                ('leoka_felony', models.SmallIntegerField(blank=True, null=True)),
                ('leoka_accident', models.SmallIntegerField(blank=True, null=True)),
                ('leoka_assault', models.IntegerField(blank=True, null=True)),
                ('leoka_status', models.SmallIntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reta_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetaMonthOffenseSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_count', models.IntegerField(blank=True, null=True)),
                ('reported_status', models.SmallIntegerField(blank=True, null=True)),
                ('unfounded_count', models.IntegerField(blank=True, null=True)),
                ('unfounded_status', models.SmallIntegerField(blank=True, null=True)),
                ('actual_count', models.IntegerField(blank=True, null=True)),
                ('actual_status', models.SmallIntegerField(blank=True, null=True)),
                ('cleared_count', models.IntegerField(blank=True, null=True)),
                ('cleared_status', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_cleared_count', models.IntegerField(blank=True, null=True)),
                ('juvenile_cleared_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reta_month_offense_subcat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetaOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_name', models.CharField(max_length=100)),
                ('offense_code', models.CharField(max_length=20, unique=True)),
                ('offense_xml_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('offense_sort_order', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reta_offense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetaOffenseCategory',
            fields=[
                ('offense_category_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('offense_category_name', models.CharField(blank=True, max_length=50, null=True)),
                ('offense_category_sort_order', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'reta_offense_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetaOffenseSubcat',
            fields=[
                ('offense_subcat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_subcat_name', models.CharField(max_length=100)),
                ('offense_subcat_code', models.CharField(max_length=20, unique=True)),
                ('offense_subcat_xml_path', models.CharField(blank=True, max_length=1000, null=True)),
                ('offense_subcat_sort_order', models.BigIntegerField(blank=True, null=True)),
                ('part', models.CharField(blank=True, max_length=1, null=True)),
                ('crime_index_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'reta_offense_subcat',
                'managed': False,
            },
        ),
    ]
