# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NibrsActivityType',
            fields=[
                ('activity_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('activity_type_code', models.CharField(blank=True, max_length=2, null=True)),
                ('activity_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_activity_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsAge',
            fields=[
                ('age_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('age_code', models.CharField(blank=True, max_length=2, null=True)),
                ('age_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_age',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsArrestee',
            fields=[
                ('arrestee_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('arrestee_seq_num', models.BigIntegerField(blank=True, null=True)),
                ('arrest_num', models.CharField(blank=True, max_length=12, null=True)),
                ('arrest_date', models.DateTimeField(blank=True, null=True)),
                ('multiple_indicator', models.CharField(blank=True, max_length=1, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('resident_code', models.CharField(blank=True, max_length=1, null=True)),
                ('under_18_disposition_code', models.CharField(blank=True, max_length=1, null=True)),
                ('clearance_ind', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('age_range_low_num', models.SmallIntegerField(blank=True, null=True)),
                ('age_range_high_num', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nibrs_arrestee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsArresteeWeapon',
            fields=[
                ('nibrs_arrestee_weapon_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nibrs_arrestee_weapon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsArrestType',
            fields=[
                ('arrest_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('arrest_type_code', models.CharField(blank=True, max_length=1, null=True)),
                ('arrest_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_arrest_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsAssignmentType',
            fields=[
                ('assignment_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('assignment_type_code', models.CharField(blank=True, max_length=1, null=True)),
                ('assignment_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_assignment_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsBiasList',
            fields=[
                ('bias_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('bias_code', models.CharField(blank=True, max_length=2, null=True)),
                ('bias_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_bias_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsBiasMotivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_bias_motivation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsCircumstances',
            fields=[
                ('circumstances_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('circumstances_type', models.CharField(blank=True, max_length=1, null=True)),
                ('circumstances_code', models.SmallIntegerField(blank=True, null=True)),
                ('circumstances_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_circumstances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsClearedExcept',
            fields=[
                ('cleared_except_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('cleared_except_code', models.CharField(blank=True, max_length=1, null=True)),
                ('cleared_except_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_cleared_except',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsCriminalAct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_criminal_act',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsCriminalActType',
            fields=[
                ('criminal_act_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('criminal_act_code', models.CharField(blank=True, max_length=1, null=True)),
                ('criminal_act_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_criminal_act_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsDrugMeasureType',
            fields=[
                ('drug_measure_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('drug_measure_code', models.CharField(blank=True, max_length=2, null=True)),
                ('drug_measure_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_drug_measure_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsEds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('data_year', models.SmallIntegerField(blank=True, null=True)),
                ('month_num', models.SmallIntegerField(blank=True, null=True)),
                ('relative_rec_num', models.IntegerField(blank=True, null=True)),
                ('segment_action_type', models.CharField(blank=True, max_length=1, null=True)),
                ('ori', models.CharField(blank=True, max_length=9, null=True)),
                ('incident_num', models.CharField(blank=True, max_length=12, null=True)),
                ('level', models.CharField(blank=True, max_length=1, null=True)),
                ('offense_code', models.CharField(blank=True, max_length=3, null=True)),
                ('person_seq_num', models.CharField(blank=True, max_length=3, null=True)),
                ('type_prop_loss', models.CharField(blank=True, max_length=1, null=True)),
                ('data_element_num', models.CharField(blank=True, max_length=3, null=True)),
                ('error_num', models.SmallIntegerField(blank=True, null=True)),
                ('data_field', models.CharField(blank=True, max_length=12, null=True)),
                ('error_msg', models.CharField(blank=True, max_length=79, null=True)),
                ('submission_ser_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nibrs_eds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsEthnicity',
            fields=[
                ('ethnicity_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('ethnicity_code', models.CharField(blank=True, max_length=1, null=True)),
                ('ethnicity_name', models.CharField(blank=True, max_length=100, null=True)),
                ('hc_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'nibrs_ethnicity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsGrpbArrest',
            fields=[
                ('grpb_arrest_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('arrest_num', models.CharField(blank=True, max_length=15, null=True)),
                ('arrest_date', models.DateTimeField(blank=True, null=True)),
                ('arrest_seq_num', models.SmallIntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=4, null=True)),
                ('arrest_type_id', models.SmallIntegerField(blank=True, null=True)),
                ('offense_type_id', models.BigIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('resident_code', models.CharField(blank=True, max_length=1, null=True)),
                ('under_18_disposition_code', models.CharField(blank=True, max_length=1, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('arrest_year', models.SmallIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('age_range_low_num', models.SmallIntegerField(blank=True, null=True)),
                ('age_range_high_num', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nibrs_grpb_arrest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsGrpbArrestWeapon',
            fields=[
                ('nibrs_grpb_arrest_weapon_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nibrs_grpb_arrest_weapon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsIncident',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('incident_number', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo_theft_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('report_date_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('incident_hour', models.SmallIntegerField(blank=True, null=True)),
                ('cleared_except_date', models.DateTimeField(blank=True, null=True)),
                ('incident_status', models.SmallIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nibrs_incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsInjury',
            fields=[
                ('injury_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('injury_code', models.CharField(blank=True, max_length=1, null=True)),
                ('injury_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_injury',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsJustifiableForce',
            fields=[
                ('justifiable_force_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('justifiable_force_code', models.CharField(blank=True, max_length=1, null=True)),
                ('justifiable_force_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_justifiable_force',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsLocationType',
            fields=[
                ('location_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('location_code', models.CharField(blank=True, max_length=2, null=True)),
                ('location_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_location_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsMonth',
            fields=[
                ('nibrs_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('month_num', models.SmallIntegerField()),
                ('data_year', models.SmallIntegerField()),
                ('reported_status', models.CharField(blank=True, max_length=1, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('update_flag', models.CharField(max_length=1)),
                ('orig_format', models.CharField(max_length=1)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=50, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nibrs_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsOffender',
            fields=[
                ('offender_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offender_seq_num', models.SmallIntegerField(blank=True, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('age_range_low_num', models.SmallIntegerField(blank=True, null=True)),
                ('age_range_high_num', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nibrs_offender',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('attempt_complete_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('num_premises_entered', models.SmallIntegerField(blank=True, null=True)),
                ('method_entry_code', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nibrs_offense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsOffenseType',
            fields=[
                ('offense_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_code', models.CharField(blank=True, max_length=5, null=True)),
                ('offense_name', models.CharField(blank=True, max_length=100, null=True)),
                ('crime_against', models.CharField(blank=True, max_length=100, null=True)),
                ('ct_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('hc_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('hc_code', models.CharField(blank=True, max_length=5, null=True)),
                ('offense_category_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_offense_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsPropDescType',
            fields=[
                ('prop_desc_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('prop_desc_code', models.CharField(blank=True, max_length=2, null=True)),
                ('prop_desc_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_prop_desc_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsProperty',
            fields=[
                ('property_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('stolen_count', models.SmallIntegerField(blank=True, null=True)),
                ('recovered_count', models.SmallIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nibrs_property',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsPropertyDesc',
            fields=[
                ('property_value', models.BigIntegerField(blank=True, null=True)),
                ('date_recovered', models.DateTimeField(blank=True, null=True)),
                ('nibrs_prop_desc_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nibrs_property_desc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsPropLossType',
            fields=[
                ('prop_loss_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('prop_loss_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_prop_loss_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsRelationship',
            fields=[
                ('relationship_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('relationship_code', models.CharField(blank=True, max_length=2, null=True)),
                ('relationship_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_relationship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsSumMonthTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nibrs_month_id', models.BigIntegerField(blank=True, null=True)),
                ('agency_id', models.BigIntegerField(blank=True, null=True)),
                ('month_num', models.SmallIntegerField(blank=True, null=True)),
                ('data_year', models.SmallIntegerField(blank=True, null=True)),
                ('reported_status', models.CharField(blank=True, max_length=1, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=50, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_ct_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_hc_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_leoka_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_arson_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('nibrs_ht_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'nibrs_sum_month_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsSuspectedDrug',
            fields=[
                ('est_drug_qty', models.FloatField(blank=True, null=True)),
                ('nibrs_suspected_drug_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nibrs_suspected_drug',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsSuspectedDrugType',
            fields=[
                ('suspected_drug_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('suspected_drug_code', models.CharField(blank=True, max_length=1, null=True)),
                ('suspected_drug_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_suspected_drug_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsSuspectUsing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_suspect_using',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsUsingList',
            fields=[
                ('suspect_using_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('suspect_using_code', models.CharField(blank=True, max_length=1, null=True)),
                ('suspect_using_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_using_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsVictim',
            fields=[
                ('victim_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('victim_seq_num', models.SmallIntegerField(blank=True, null=True)),
                ('outside_agency_id', models.BigIntegerField(blank=True, null=True)),
                ('age_num', models.SmallIntegerField(blank=True, null=True)),
                ('sex_code', models.CharField(blank=True, max_length=1, null=True)),
                ('resident_status_code', models.CharField(blank=True, max_length=1, null=True)),
                ('agency_data_year', models.SmallIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('age_range_low_num', models.SmallIntegerField(blank=True, null=True)),
                ('age_range_high_num', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nibrs_victim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsVictimCircumstances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_victim_circumstances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsVictimInjury',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_victim_injury',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsVictimOffenderRel',
            fields=[
                ('nibrs_victim_offender_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nibrs_victim_offender_rel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsVictimOffense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'nibrs_victim_offense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsVictimType',
            fields=[
                ('victim_type_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('victim_type_code', models.CharField(blank=True, max_length=1, null=True)),
                ('victim_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'nibrs_victim_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsWeapon',
            fields=[
                ('nibrs_weapon_id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nibrs_weapon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NibrsWeaponType',
            fields=[
                ('weapon_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('weapon_code', models.CharField(blank=True, max_length=3, null=True)),
                ('weapon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('shr_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'nibrs_weapon_type',
                'managed': False,
            },
        ),
    ]
