# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HtMonth',
            fields=[
                ('ht_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('data_home', models.CharField(max_length=1)),
                ('source_flag', models.CharField(max_length=1)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_by_user', models.CharField(blank=True, max_length=100, null=True)),
                ('prepared_by_email', models.CharField(blank=True, max_length=200, null=True)),
                ('orig_format', models.CharField(max_length=1)),
                ('total_reported_count', models.IntegerField(blank=True, null=True)),
                ('total_unfounded_count', models.IntegerField(blank=True, null=True)),
                ('total_actual_count', models.IntegerField(blank=True, null=True)),
                ('total_cleared_count', models.IntegerField(blank=True, null=True)),
                ('total_juvenile_cleared_count', models.IntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ht_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HtMonthOffenseSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_count', models.IntegerField(blank=True, null=True)),
                ('reported_status', models.SmallIntegerField(blank=True, null=True)),
                ('unfounded_count', models.IntegerField(blank=True, null=True)),
                ('unfounded_status', models.SmallIntegerField(blank=True, null=True)),
                ('actual_count', models.IntegerField(blank=True, null=True)),
                ('actual_status', models.SmallIntegerField(blank=True, null=True)),
                ('cleared_count', models.IntegerField(blank=True, null=True)),
                ('cleared_status', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_cleared_count', models.IntegerField(blank=True, null=True)),
                ('juvenile_cleared_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ht_month_offense_subcat',
                'managed': False,
            },
        ),
    ]
