# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuppLarcenyType',
            fields=[
                ('larceny_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('larceny_type_name', models.CharField(max_length=100)),
                ('larceny_type_code', models.CharField(max_length=20)),
                ('larceny_xml_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'supp_larceny_type',
            },
        ),
        migrations.CreateModel(
            name='SuppMonth',
            fields=[
                ('supp_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('data_home', models.CharField(max_length=1)),
                ('source_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_flag', models.CharField(max_length=1)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('orig_format', models.CharField(max_length=1)),
                ('mv_stolen_local_rec_local', models.BigIntegerField(blank=True, null=True)),
                ('mv_stolen_local_rec_other', models.BigIntegerField(blank=True, null=True)),
                ('mv_tot_local_stolen_rec', models.BigIntegerField(blank=True, null=True)),
                ('mv_stolen_other_rec_local', models.BigIntegerField(blank=True, null=True)),
                ('mv_stolen_status', models.SmallIntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'supp_month',
            },
        ),
        migrations.CreateModel(
            name='SuppOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_name', models.CharField(max_length=100)),
                ('offense_code', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'supp_offense',
            },
        ),
        migrations.CreateModel(
            name='SuppOffenseSubcat',
            fields=[
                ('offense_subcat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_subcat_name', models.CharField(max_length=100)),
                ('offense_subcat_code', models.CharField(max_length=20)),
                ('offense_subcat_xml_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'supp_offense_subcat',
            },
        ),
        migrations.CreateModel(
            name='SuppPropByOffenseSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_count', models.IntegerField(blank=True, null=True)),
                ('actual_status', models.SmallIntegerField(blank=True, null=True)),
                ('stolen_value', models.BigIntegerField(blank=True, null=True)),
                ('stolen_value_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'supp_prop_by_offense_subcat',
            },
        ),
        migrations.CreateModel(
            name='SuppPropertyByTypeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stolen_value', models.BigIntegerField(blank=True, null=True)),
                ('stolen_value_status', models.SmallIntegerField(blank=True, null=True)),
                ('recovered_value', models.BigIntegerField(blank=True, null=True)),
                ('recovered_value_status', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'supp_property_by_type_value',
            },
        ),
        migrations.CreateModel(
            name='SuppPropertyType',
            fields=[
                ('prop_type_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('prop_type_name', models.CharField(max_length=100)),
                ('prop_type_code', models.CharField(max_length=20)),
                ('prop_type_code_num', models.SmallIntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'supp_property_type',
            },
        ),
    ]
