# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ref', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsrAgeRange',
            fields=[
                ('age_range_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('age_range_name', models.CharField(blank=True, max_length=20, null=True)),
                ('age_range_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('juvenile_flag', models.CharField(max_length=1)),
                ('ff_sort_order', models.CharField(blank=True, max_length=3, null=True)),
                ('age_sex', models.CharField(blank=True, max_length=1, null=True)),
                ('xml_code', models.CharField(blank=True, max_length=2001, null=True)),
            ],
            options={
                'db_table': 'asr_age_range',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsrAgeSexSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrest_count', models.IntegerField(blank=True, null=True)),
                ('arrest_status', models.SmallIntegerField(blank=True, null=True)),
                ('active_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('age_range', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asr.AsrAgeRange')),
            ],
            options={
                'db_table': 'asr_age_sex_subcat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsrEthnicity',
            fields=[
                ('ethnicity_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ethnicity_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ethnicity_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('ff_sort_order', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'asr_ethnicity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsrEthnicityOffense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juvenile_flag', models.CharField(max_length=1)),
                ('arrest_count', models.IntegerField(blank=True, null=True)),
                ('arrest_status', models.SmallIntegerField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asr_ethnicity_offense',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsrMonth',
            fields=[
                ('asr_month_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_year', models.SmallIntegerField()),
                ('month_num', models.SmallIntegerField()),
                ('source_flag', models.CharField(max_length=1)),
                ('reported_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'asr_month',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsrOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_name', models.CharField(blank=True, max_length=100, null=True)),
                ('offense_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('total_flag', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'asr_offense',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsrOffenseCategory',
            fields=[
                ('offense_cat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_cat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('offense_cat_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'asr_offense_category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsrOffenseSubcat',
            fields=[
                ('offense_subcat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('offense_subcat_name', models.CharField(blank=True, max_length=100, null=True)),
                ('offense_subcat_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('srs_offense_code', models.CharField(blank=True, max_length=3, null=True)),
                ('master_offense_code', models.SmallIntegerField(blank=True, null=True)),
                ('total_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('adult_juv_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('offense', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asr.AsrOffense')),
            ],
            options={
                'db_table': 'asr_offense_subcat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsrRaceOffenseSubcat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('juvenile_flag', models.CharField(max_length=1)),
                ('arrest_count', models.IntegerField(blank=True, null=True)),
                ('arrest_status', models.SmallIntegerField(blank=True, null=True)),
                ('active_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asr_race_offense_subcat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AsrJuvenileDisposition',
            fields=[
                ('asr_month', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='asr.AsrMonth')),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('handled_within_dept', models.IntegerField(blank=True, null=True)),
                ('juvenile_court', models.IntegerField(blank=True, null=True)),
                ('welfare_agency', models.IntegerField(blank=True, null=True)),
                ('other_police', models.IntegerField(blank=True, null=True)),
                ('adult_court', models.IntegerField(blank=True, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asr_juvenile_disposition',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='asrraceoffensesubcat',
            name='asr_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asr.AsrMonth'),
        ),
        migrations.AddField(
            model_name='asrraceoffensesubcat',
            name='offense_subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asr.AsrOffenseSubcat'),
        ),
        migrations.AddField(
            model_name='asrraceoffensesubcat',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefRace'),
        ),
        migrations.AddField(
            model_name='asroffense',
            name='offense_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asr.AsrOffenseCategory'),
        ),
        migrations.AddField(
            model_name='asrmonth',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefAgency'),
        ),
        migrations.AddField(
            model_name='asrethnicityoffense',
            name='asr_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asr.AsrMonth'),
        ),
        migrations.AddField(
            model_name='asrethnicityoffense',
            name='ethnicity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asr.AsrEthnicity'),
        ),
        migrations.AddField(
            model_name='asrethnicityoffense',
            name='offense_subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asr.AsrOffenseSubcat'),
        ),
        migrations.AddField(
            model_name='asragesexsubcat',
            name='asr_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asr.AsrMonth'),
        ),
        migrations.AddField(
            model_name='asragesexsubcat',
            name='offense_subcat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='asr.AsrOffenseSubcat'),
        ),
        migrations.AlterUniqueTogether(
            name='asrraceoffensesubcat',
            unique_together=set([('asr_month', 'offense_subcat', 'race', 'juvenile_flag')]),
        ),
        migrations.AlterUniqueTogether(
            name='asrmonth',
            unique_together=set([('agency', 'data_year', 'month_num', 'data_home')]),
        ),
        migrations.AlterUniqueTogether(
            name='asrethnicityoffense',
            unique_together=set([('asr_month', 'offense_subcat', 'ethnicity', 'juvenile_flag')]),
        ),
        migrations.AlterUniqueTogether(
            name='asragesexsubcat',
            unique_together=set([('asr_month', 'offense_subcat', 'age_range')]),
        ),
    ]
