# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ref', '0001_initial'),
        ('nibrs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HcBiasMotivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsBiasList')),
            ],
            options={
                'db_table': 'hc_bias_motivation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HcIncident',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('incident_no', models.CharField(blank=True, max_length=20, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('source_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('adult_victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('incident_status', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('offender_count', models.SmallIntegerField(blank=True, null=True)),
                ('adult_offender_count', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_offender_count', models.SmallIntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_incident_id', models.BigIntegerField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefAgency')),
            ],
            options={
                'db_table': 'hc_incident',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HcOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hc.HcIncident')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsLocationType')),
                ('offense_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsOffenseType')),
            ],
            options={
                'db_table': 'hc_offense',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HcQuarter',
            fields=[
                ('quarter_num', models.SmallIntegerField()),
                ('data_year', models.SmallIntegerField()),
                ('reported_status', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_count', models.BigIntegerField(blank=True, null=True)),
                ('hc_quarter_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(max_length=1)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefAgency')),
            ],
            options={
                'db_table': 'hc_quarter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HcVictim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hc.HcOffense')),
                ('victim_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsVictimType')),
            ],
            options={
                'db_table': 'hc_victim',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='hcincident',
            name='hc_quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hc.HcQuarter'),
        ),
        migrations.AddField(
            model_name='hcincident',
            name='offender_ethnicity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nibrs.NibrsEthnicity'),
        ),
        migrations.AddField(
            model_name='hcincident',
            name='offender_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ref.RefRace'),
        ),
        migrations.AddField(
            model_name='hcbiasmotivation',
            name='offense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hc.HcOffense'),
        ),
        migrations.AlterUniqueTogether(
            name='hcvictim',
            unique_together=set([('offense', 'victim_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='hcquarter',
            unique_together=set([('agency', 'quarter_num', 'data_year', 'data_home')]),
        ),
        migrations.AlterUniqueTogether(
            name='hcbiasmotivation',
            unique_together=set([('offense', 'bias')]),
        ),
    ]
