# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HcBiasMotivation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hc_bias_motivation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcIncident',
            fields=[
                ('incident_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('incident_no', models.CharField(blank=True, max_length=20, null=True)),
                ('incident_date', models.DateTimeField(blank=True, null=True)),
                ('data_home', models.CharField(blank=True, max_length=1, null=True)),
                ('source_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('prepared_date', models.DateTimeField(blank=True, null=True)),
                ('victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('adult_victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('incident_status', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('offender_count', models.SmallIntegerField(blank=True, null=True)),
                ('adult_offender_count', models.SmallIntegerField(blank=True, null=True)),
                ('juvenile_offender_count', models.SmallIntegerField(blank=True, null=True)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('nibrs_incident_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hc_incident',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcOffense',
            fields=[
                ('offense_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('victim_count', models.SmallIntegerField(blank=True, null=True)),
                ('nibrs_offense_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hc_offense',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcQuarter',
            fields=[
                ('quarter_num', models.SmallIntegerField()),
                ('data_year', models.SmallIntegerField()),
                ('reported_status', models.CharField(blank=True, max_length=1, null=True)),
                ('reported_count', models.BigIntegerField(blank=True, null=True)),
                ('hc_quarter_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('update_flag', models.CharField(blank=True, max_length=1, null=True)),
                ('orig_format', models.CharField(blank=True, max_length=1, null=True)),
                ('ff_line_number', models.BigIntegerField(blank=True, null=True)),
                ('ddocname', models.CharField(blank=True, max_length=100, null=True)),
                ('did', models.BigIntegerField(blank=True, null=True)),
                ('data_home', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'hc_quarter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HcVictim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'hc_victim',
                'managed': False,
            },
        ),
    ]
